logging:
  version: 1
  handlers:
    file:
      class: logging.handlers.RotatingFileHandler
      filename: /var/log/dask.log
      level: INFO
    console:
      class: logging.StreamHandler
      level: INFO
  loggers:
    distributed.worker:
      level: INFO
      handlers:
        - file
        - console
    distributed.scheduler:
      level: INFO
      handlers:
        - file
        - console
